import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import {Authentication} from "../services/utils"
import Link from "next/link"

export default function Home() {

  const obj = new Authentication()

  interface Fylo {
    title:string,
    icon:string,
    desc:string
  }

  interface Test {
    name:string,
    image:string,
    desc:string,
    pos:string
  }

  const Testimonials:Test[] = [
    {
      name:"Johnson",
      image:"/images/profile-1.jpg",
      desc:"FyloShare has improved our productivity by an order of magnitude. Since making the switched our team has becomed a well-oiled collaboration machine",
      pos:"Product Manger"
    },
    {
      name:"Bruce Mckenzie",
      image:"/images/profile-2.jpg",
      desc:"FyloShare has improved our productivity by an order of magnitude. Since making the switched our team has becomed a well-oiled collaboration machine",
      pos:"Business Manager, Huddler"
    },
    {
      name:"Ivan Boyd",
      image:"/images/profile-3.jpg",
      desc:"FyloShare has improved our productivity by an order of magnitude. Since making the switched our team has becomed a well-oiled collaboration machine",
      pos:"Founder & CEO, Huddle"
    },
  ]
  const fyloarray :Fylo[] = [
    {
      title:"Access your files anywhere",
      icon:"/images/icon-access-anywhere.svg",
      desc:"The ability to use smartphones,tablets,computer to access your account means your files follows you everywhere."
    },
    {
      title:"Security you can trust",
      icon:"/images/icon-security.svg",
      desc:"2-factor authentication and user-controlled encryption are just a couple of security features we allow to secure your files."
    },
    {
      title:"Real time-collaboration",
      icon:"/images/icon-collaboration.svg",
      desc:"Securely share files and folders with friends and families and collegues for collaboration. No email attachments required."
    },  {
      title:"Store any type of files",
      icon:"/images/icon-any-file.svg",
      desc:"Whether you are sharing holiday photos or work documents,Fylo gats you covered allowing for all file types to be securely shared and stored."
    }
  ]
  return (
    <>
      <Head>
        <title>FyloShare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>

      <Navbar/>

      <header className='flex items-center justify-center mt-[100px] flex-col gap-[50px] px-3'>
        <Image src="/images/illustration-intro.png" width={600} height={300} alt="icon"/>
      </header>
<div className='  text-white mt-[160px] px-3' >
  <div className='flex flex-col items-center justify-center'> 
  <h1 className='text-3xl text-center -mt-[70px] py-4'>All your files in one secure location,<br/>accessible anywhere</h1>
  <p className='mt-[20px] md:w-[550px] text-center text-sm'>Fylo stores all your important files in one location. Access them whenever you need,share and collaborate with friends and families, co-workers</p>
  <div className='mt-[20px]'><Link href="/auth/signup"><button className="bg-[#54CED5] text-white w-[200px] rounded-full p-2" >Get Started</button></Link></div>
  <p></p>

  </div>


  <div className='flex items-center justify-center mt-[100px]'>

    <div className='grid grid-cols-1 md:grid-cols-2 gap-[150px] px-3'>
      {
        fyloarray.map((item:Fylo,index:number)=>{
          return (
            <div key={index} className="flex flex-col items-center justify-center">
              <Image src={item.icon} width={100} height={100} alt="icon"/>
              <div className='mt-[25px]'>
                <h3 className='font-bold text-center mb-[15px]'>{item.title}</h3>
                <p className='text-center w-[350px]'>{item.desc}</p>
              </div>

            </div>
          )
        })
      }
    </div>

  </div>

  <div className='flex items-center justify-center mt-[120px]'>

    <div className='flex items-center justify-center gap-[30px] flex-col md:flex-row'>
      <div>
      <Image src="/images/illustration-stay-productive.png" width={400} height={100} alt="icon"/>
      </div>
      <div>
        <h1 className='text-3xl font-bold mb-[15px]'>Stay productive,<br/> wherever you are</h1>
        <p className='md:w-[450px] mb-[30px] text-sm'>Never let location be an issue when locating your files, Fylo has you covered for all your file storage needs.</p>
        <p className='md:w-[450px] text-sm'>Securely share files and folders with friends,family and colleagues for live collaboration. No email attachments.</p>
      </div>
    </div>
  </div>

 

</div>

<div className="flex items-center justify-center mt-[100px] relative mb-[200px] px-3">
<div className="absolute -top-[30px] md:left-[100px] left-0 z-2 px-3"><Image src="/images/bg-quotes.png" width={50} height={50} alt="quotes"/></div>
  <div className='grid grid-cols-1 md:grid-cols-3 gap-[30px] z-10 '>
    {
      Testimonials.map((item:Test,index:number)=>{
      return( <div key={index} className="bg-[#212839] p-4 md:w-[350px] shadow-2xl">
          <p className='text-sm'>{item.desc}</p>
          <div className='flex gap-[15px] mt-[15px]'>
<Image src={item.image} width={40} height={50} alt="icon" className='rounded-full'/>
<div>
  <h3 className='font-bold text-sm'>{item.name}</h3>
  <p className='' style={{fontSize:'10px'}}>{item.pos}</p>
</div>
          </div>
        </div>)
      })
    }
  </div>
</div>

<Footer/>
    </>
  )
}
